-- Supabase SQL Schema for TERRA

-- 1. Tabla de historial biográfico
create table if not exists historia (
  id bigint generated by default as identity primary key,
  texto text not null,
  created_at timestamptz default now()
);

-- 2. Tabla de redes sociales
create table if not exists redes (
  id bigint generated by default as identity primary key,
  nombre text not null,
  url text not null,
  orden int default 0,
  created_at timestamptz default now()
);

-- 3. Tabla de discografía
create table if not exists discografia (
  id bigint generated by default as identity primary key,
  tipo text not null,
  nombre text not null,
  year text not null,
  spotify_url text,
  youtube_url text,
  cover_path text,
  cover_url text,
  created_at timestamptz default now()
);

-- 4. Tabla de recitales / novedades
create table if not exists recitales (
  id bigint generated by default as identity primary key,
  ciudad text not null,
  fecha text not null,
  hora text not null,
  direccion text not null,
  instagram_url text,
  flyer_path text,
  flyer_url text,
  created_at timestamptz default now()
);

-- 5. Tabla de El Club
create table if not exists el_club (
  id bigint generated by default as identity primary key,
  descripcion text,
  playlist_url text,
  created_at timestamptz default now()
);

-- 6. Tabla de Merchandising
create table if not exists merch (
  id bigint generated by default as identity primary key,
  nombre text not null,
  image_path text,
  image_url text,
  created_at timestamptz default now()
);

-- Usuarios autorizados a administrar el contenido. Se completa únicamente
-- desde SQL Editor/Dashboard usando el UUID de una cuenta de auth.users.
create table if not exists admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

-- Indexes optional for performance
create index if not exists idx_redes_orden on redes (orden);
create index if not exists idx_discografia_year on discografia (year);
create index if not exists idx_recitales_fecha on recitales (fecha);

-- Buckets configuration (run via Supabase dashboard or CLI if supported)
-- Buckets: flyers, discografia, merch
-- Access settings: public read access for assets, private write via Supabase Storage policies.

-- IMPORTANTE: después de crear las tablas, ejecutar la migración no destructiva
-- supabase/migrations/20260910_admin_security.sql para habilitar RLS y las
-- políticas de tablas/Storage. No se debe usar este esquema para recrear tablas
-- que ya contienen datos.

-- Nota: Supabase SQL nativo no crea buckets; úsese dashboard o CLI:
-- supabase storage bucket create flyers --public
-- supabase storage bucket create discografia --public
-- supabase storage bucket create merch --public
