-- FASE 1: noticias administrables para la landing de TERRA.
-- Esta migración es aditiva y no modifica tablas ni policies existentes.

create table if not exists public.novedades (
  id bigint generated by default as identity primary key,
  titulo text not null check (length(trim(titulo)) > 0),
  descripcion text,
  fecha date,
  imagen_path text,
  imagen_url text,
  url text,
  texto_boton text,
  destacada boolean not null default false,
  visible boolean not null default true,
  orden integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.novedades is 'Noticias breves y anuncios publicados en la landing de TERRA.';
comment on column public.novedades.fecha is 'Fecha editorial o fecha relacionada con el anuncio; es independiente de created_at.';
comment on column public.novedades.orden is 'Prioridad manual ascendente dentro de cada grupo; los valores menores aparecen primero.';

create index if not exists idx_novedades_public_order
  on public.novedades (destacada desc, orden asc, fecha desc)
  where visible = true;

create or replace function public.set_novedades_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists novedades_set_updated_at on public.novedades;
create trigger novedades_set_updated_at
before update on public.novedades
for each row execute function public.set_novedades_updated_at();

alter table public.novedades enable row level security;

-- Visitantes y usuarios autenticados sólo pueden leer noticias publicadas.
create policy "terra_news_public_read"
on public.novedades
for select
to anon, authenticated
using (visible = true);

-- La policy adicional permite que el Admin también consulte noticias ocultas.
create policy "terra_news_admin_read"
on public.novedades
for select
to authenticated
using (public.is_admin());

create policy "terra_news_admin_insert"
on public.novedades
for insert
to authenticated
with check (public.is_admin());

create policy "terra_news_admin_update"
on public.novedades
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "terra_news_admin_delete"
on public.novedades
for delete
to authenticated
using (public.is_admin());

-- Bucket público para que getPublicUrl funcione en la landing. Las escrituras
-- siguen protegidas con policies específicas sobre storage.objects.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'novedades',
  'novedades',
  true,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

create policy "terra_news_storage_public_read"
on storage.objects
for select
to public
using (bucket_id = 'novedades');

create policy "terra_news_storage_admin_insert"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'novedades' and public.is_admin());

create policy "terra_news_storage_admin_update"
on storage.objects
for update
to authenticated
using (bucket_id = 'novedades' and public.is_admin())
with check (bucket_id = 'novedades' and public.is_admin());

create policy "terra_news_storage_admin_delete"
on storage.objects
for delete
to authenticated
using (bucket_id = 'novedades' and public.is_admin());
